### ISSUE TITLE
MultiQC config file for WES

### ISSUE THREAD

**Issue by sophie22** [eastgenomics/egg4_dias_WES_config#1]
uploaded into [001](https://platform.dnanexus.com/projects/Fkb6Gkj433GVVvj73J7x8KbV/data/dynamic_files/multiqc_config), project-Fkb6Gkj433GVVvj73J7x8KbV:file-G2GZppj433GQJjb4Fzx8635z

**Comment by sophie22** [comment]
version 1.0.1 of the file is coming, please don't use the one above

**Comment by sophie22** [comment]
v1.0.1 file ID: project-Fkb6Gkj433GVVvj73J7x8KbV:file-G2J512Q433GyQgFVGyBZpxpF

**Comment by mattgarner** [comment]
Done in v1.0.0
